import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Sidebar from "@/components/Sidebar ";
import Header from "@/components/header";
import Hooter from "@/components/hooter";
import { SidebarProvider } from "@/context/SidebarContext"; // インポート

const geistSans = localFont({
	src: "./fonts/GeistVF.woff",
	variable: "--font-geist-sans",
	weight: "100 900",
});
const geistMono = localFont({
	src: "./fonts/GeistMonoVF.woff",
	variable: "--font-geist-mono",
	weight: "100 900",
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased`}
			>
				{/* SidebarContext Provider */}
				<SidebarProvider>
					{/* ヘッダー */}
					<Header />

					{/* サイドバーとコンテンツ */}
					<div className="flex">
						{/* サイドバー */}
						<Sidebar />

						{/* メインコンテンツ */}
						<main className="flex-1 p-4 mt-[64px]">{children}</main>
					</div>

					{/* フッター */}
					<Hooter />
				</SidebarProvider>
			</body>
		</html>
	);
}
