import Sidebar from "@/components/Sidebar ";
import Header from "@/components/header";
import Hooter from "@/components/hooter";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Header />
        <div className="flex">
          <Sidebar />
          <main className="mt-[64px] flex-1 p-4">{children}</main>
        </div>
        <Hooter />
      </body>
    </html>
  );
}
